pipeline {
    agent any 
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage('sonar-scan1'){
            steps{
        withSonarQubeEnv('sonarqube'){
    sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=jessica-devops_geo-app'
        }
    }
}
        stage("maven"){
            steps {
                sh 'mvn clean'
                sh 'mvn validate'
                sh 'mvn compile'
                sh 'mvn install'
                sh 'mvn test'
                sh 'mvn package'
            }
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP9JbqJa5kXmjT1uzyAMatwXhrC -T \
                  target/bio*jar \
                  "http://34.207.64.230:8081/artifactory/geolocation/bio_${BUILD_ID}.jar"'
            }
        }
    }
}
