pipeline {
    agent any 
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage('sonar-scan1'){
            steps{
        withSonarQubeEnv('sonarqube'){
    sh'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectkey-it jessica-devops'
        }
    }
}
        stage("maven"){
            steps {
                sh 'mvn clean'
                sh 'mvn validate'
                sh 'mvn compile'
                sh 'mvn install'
                sh 'mvn test'
                sh 'mvn package'
            }
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP7sErwo11qeXL295T6doA3daaj -T \
                 target/bio*.jar \
                  "http://54.89.119.58:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            }
        }
    }
}
