pipeline {
    agent any 
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage("maven"){
            steps {
                sh 'mvn clean'
                sh 'mvn validate'
                sh 'mvn compile'
                sh 'mvn install'
                sh 'mvn test'
                sh 'mvn package'
            }
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP9LYZRyUvZo7aHFvCFDuqgk6vN -T \
                target/bio*jar \
                 "http://34.207.211.71:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            }
        }
    }
}